### PR TITLE
Travis build

### PR DESCRIPTION
**Pull request by nschonni**
Adds CI build and checking. This currently fails because of a number of missing alt tags and dead links.

### CODE REVIEW

**Comment by nschonni** [comment]
@pjackson28 or @LaurentGoderre you'll need to setup the Travis hook
You can see the current failurues here https://travis-ci.org/nschonni/wet-boew-jekyll/builds/23238330 but I'm going to land this as-is

**Comment by pjackson28** [comment]
@nschonni The errors only seem to be coming from the v3.1 branch. Can it be excluded from the checking? I also noted that these are false failures because WCAG 2.0 allows you to null out the alt text when an image is included in a link with other descriptive link text (which is the case for each of those errors).

**Comment by nschonni** [comment]
> The errors only seem to be coming from the v3.1 branch

Not sure what you're refering to here, can you point to a specific section that is 3.1 related? 

The alt tags can now be ignored for specific patterns like the logos https://github.com/gjtorikian/html-proofer#configuration

**Comment by pjackson28** [comment]
All the image URLs are for v3.1 only (include "v3.1-ci"). In fact the files themselves don't even appear in the markup in v4.0.

**Pull request merged**
